### ISSUE TITLE
Web app login

### ISSUE THREAD

**Issue by FirstNerd** [usableprivacy/upribox#101]
Fresh install of version 1 on pi 3 B, only silent mode active.  Try to login to web app and I get a server error 500.

**Comment by markushuber** [comment]
Hi @FirstNerd, we will investigate the issue - thanks for reporting it.

**Comment by FirstNerd** [comment]
![screenshot_2017-11-11-19-25-32](https://user-images.githubusercontent.com/32230471/32695031-94c3c67e-c716-11e7-9927-61d5946a2cf5.jpg)
![screenshot_2017-11-11-19-22-39](https://user-images.githubusercontent.com/32230471/32695032-94e3125e-c716-11e7-9f71-8bda9a2abee3.jpg)

screenshots of me able to ssh into the pi3 while running upribox v1 img 
with nginx status and nginx error log.. if anymore info is needed let me know I'm glad to help

**Comment by markushuber** [comment]
Thanks for reporting this issue @FirstNerd. I triaged the problem and committed a fix (redis-server was failing due to an inaccessible logfile). Update should reach your box withing four hours.
Please let us know if the commit fixed your issue.

**Comment by FirstNerd** [comment]
anyway I can force an update via ssh terminal to check if the issue been resolved?

**Comment by FirstNerd** [comment]
Issue resolved....
