### ISSUE TITLE
Inkonsistente Anleitungsgrafiken

### ISSUE THREAD

**Issue by chrisi092** [usableprivacy/upribox#108]
Ein generelles Problem, welches im Bezug auf die Papieranleitung
festgestellt wurde, ist, dass ein Line-Icon-Grafikstil zur Anwendung kam
der sich in keinem der anderen Identity Bestandteile wiederfindet.

3 Grafiken wurden im Stil jener Grafiken welche auch auf der „Getting-Started“ Seite
der Upribox verwendet werden erstellt - diese sollten in die Papierillustration
eingebaut werden.

**Comment by christianbrandl** [comment]
Wo finde ich diese Grafiken?

**Comment by chrisi092** [comment]
Die Grafiken wurden an Markus zur Bestätigung versendet. Sobald es das okay dafür gibt, leite ich sie weiter.
