### ISSUE TITLE
Wochenstatistik Hover-Daten auf unterschiedlichen Seiten

### ISSUE THREAD

**Issue by chrisi092** [usableprivacy/upribox#111]
Auf der Statistikseite der Adminoberfläche wurden Inkonsistenzen im
Bezug auf die Darstellung der bei Hover eingeblendeten
Zusatzinformationen (gesplittete Zahlenwerte zu geblockt und gefiltert)
festgestellt. Diese werden je nach Säule einmal rechts von der
Datensäule dargestellt und einmal links.
Sollte es möglich sein dies anzupassen, ist anzuraten
diese Inkonsistenz im Design auszubessern.

**Comment by tobiasdam** [comment]
Die Darstellung der Hover-Daten wird von der Library automatisch gehandhabt. Es ist lediglich möglich die Konfiguration zu ändern, sodass die Hover-Daten in den meisten Fällen einheitlich auf einer Seite angezeigt werden. Jedoch verschmälern diese Änderungen das Diagramm in der mobilen Ansicht erheblich, sodass auf diese Änderung verzichtet wird.
