### ISSUE TITLE
Abbrechen ist kein Button sondern hat Formatierung eines Links

### ISSUE THREAD

**Issue by chrisi092** [usableprivacy/upribox#114]
Auf der Adminoberfläche wird generell für „Abbrechen“ kein Button
verwendet sondern die im Styleguide definierte Formatierung für Links.

Sollte dies wichtigen, notwendigen Zweck erfüllen, sollte
die Abbrechen Funktion auch die Formatierung eines Buttons erhalten.

**Comment by markushuber** [comment]
Could you provide us with the correct CSS/HTML snippet to fix this @chrisi092
