### ISSUE TITLE
Status-Inkonsistenzen Speicher-Button 

### ISSUE THREAD

**Issue by chrisi092** [usableprivacy/upribox#115]
Generell ist die hellblaue Hover-Version des Buttons im Styleguide nicht
auffindbar. In der Adminoberfläche wird der aktive dunkelblaue Button-
Zustand auch verwendet wenn noch nicht alle benötigten 
Eingabefelder ausgefüllt sind.

Es sollten ergänzende Informationen zu den Zuständen
für welche die jeweiligen Button-Styles verwendet werden im
Styleguide angegeben werden. Generell sollte sichergestellt werden,
dass der aktive Buttonzustand nur dann getriggered wird wenn alle
benötigten Felder ausgefüllt sind, ansonsten sollte er in seiner grauen
Variante vorzufinden sein.

**Comment by markushuber** [comment]
@chrisi092 could you support this issues with CSS fixes for @tobiasdam ?
