### ISSUE TITLE
Inkonsistenz durch Ausblendung von Breadcrumbs, Nav etc.

### ISSUE THREAD

**Issue by chrisi092** [usableprivacy/upribox#117]
Beim Setup Prozess kommt es zu einem Bruch mit dem Rest der
Admin-Oberfläche, da sowohl die Side- und Topnavigation komplett
ausgeblendet werden. Auch die Icons zum Logout und zum Verweis
auf das Nutzer-Panel finden sich nicht mehr. Weiters gibt es im
Gegensatz zur restlichen Seite keinen Abbrechen Button im Setup-
Prozess.

Sollte dies keinen wichtigen Zweck erfüllen sollte der
Setup-Prozess an den Rest der Administrationsoberfläche angeglichen
werden.

**Comment by tobiasdam** [comment]
Aufgrund des Ablaufs des Setup-Prozesses ist es nicht erwünscht, dass der Nutzer mithilfe des Webinterfaces das Setup abbricht bzw. von dem Setup weg navigiert.
