### ISSUE TITLE
mydealz ( Zum Deal ) Seite wird geblockt

### ISSUE THREAD

**Issue by intrepid-ibex** [usableprivacy/upribox#120]
Eine zusätzliche Sache ist mir aufgefallen. 

Wir besuchen schon mal diese Webseite : 

https://www.mydealz.de/ 

Das ist eine Seite für interessante Schnäppchen im Internet. 
Auf der rechten Seite der Webseite befindet sich eine grüne Schaltfläche mit 
weißem Text ( Zum Deal ). 
Wenn sich die UPRIBOX im Netzwerk befindet, funktioniert dieser Link nicht 
mehr.  Es wird eine leere Seite angezeigt.

**Comment by markushuber** [comment]
Vielen Dank @intrepid-ibex 
Dieses Issue ist ein Duplikat von #36 und schließe es daher vorerst.
