### ISSUE TITLE
Changing the mode of a device might be really slow

### ISSUE THREAD

**Issue by tobiasdam** [usableprivacy/upribox#121]
In case no device is connected to the upribox wifi, changing the mode of a device is really slow (more than 90s). 

For some reason ntopng does not terminate after receiving `SIGTERM` via systemd and is killed after the default timeout of 90 seconds via `SIGKILL`. This is only the case if ntopng does not receive any traffic on a listening interface.

This seems to be related to [this issue](https://github.com/ntop/ntopng/issues/1424).

**Comment by markushuber** [comment]
This issue has been fixed by stopping to rewrite the ntopng config on device state changes (https://github.com/usableprivacy/upribox/commit/853eefa3757155335a7386280ccb550a7709123e)
