### ISSUE TITLE
How to actually enable ninja mode?

### ISSUE THREAD

**Issue by maxkarak** [usableprivacy/upribox#141]
This is a stupid question, but I have been reading the docs and going through past issues, but still have come up with nothing.  

I have set up a raspberry pi 3 (w/ internal wifi) and the upribox wifi network shows up.  I can login via the web or ssh and do the usual stuff.  Subsequently I acquired a TL-WN722N (old, Atheros version), and plugged it in.  dmegs confirms it is detected.  

What must I do now?  how do I actually tell it to create the upribox-ninja wifi ssid, etc?

many thanks in advance for any help.  regards

**Comment by markushuber** [comment]
Hi @maxkarak,
With version 2 we deprecated the feature of a separate Ninja SSID. 
We now rely on a single SSID and each device can be set to a certain mode individually.
In order to set your device into Ninja mode you need to do this via the Web-UI.

**Comment by maxkarak** [comment]
Dear Markus, thank you for your reply.  I did try to enable ninja mode on a few select devices through the web gui, but I lost internet connectivity..  It must be due to my local setup, I will keep trying.  best regards.

**Comment by markushuber** [comment]
Could you solve your local setup yet @maxkarak? If you think you are loosing network connectivity because of a upribox bug - help us to track down the issue with more information.

**Comment by maxkarak** [comment]
Hi Markus, I have been traveling and have not had time to investigate, but I believe the problem is with my pfsense setup, not upribox.   thank you for a great project!....
