### ISSUE TITLE
Static IP configuration, Server Error (500) , upribox 2.0

### ISSUE THREAD

**Issue by intrepid-ibex** [usableprivacy/upribox#148]
When I click Static IP configuration, I get Server Error (500)
What happens?

**Comment by markushuber** [comment]
Hi @intrepid-ibex unfortunately I could not reproduce the issue you experienced with static IP settings in the web interface.

Do you still have the issue?
It would be helpful if you could provide debug information via Email: https://upribox.org/kontakt/
Debug information required: latest backup from `/var/upribox-backups/weekly`

**Comment by intrepid-ibex** [comment]
Hi, when I try to access the weekly folder , i got "permission denied".
On my PI the green LED is always ON, and the red LED is always OUT.
Is this correct?
Best regards.

**Comment by markushuber** [comment]
Once the upribox has completed the startup, the green LED will be always on while the red LED is out - this is expected.
The backup files are protected from access via a standard user, run `sudo su` to become root before accessing the backup-files.
