### ISSUE TITLE
upribox web-inteface not reachable

### ISSUE THREAD

**Issue by intrepid-ibex** [usableprivacy/upribox#150]
I have to change my router ( from O2 to Unitymedia ), after the change all works fine.

It seems, the is upribox is working.
I can connect to the upribox wifi network.
But now I have no connection to the upribox web-interface ( http://upri.box ).
SSH connection to the upribox ( PUTTY ) is working.

How can I connect to the upribox web-interface?

Best regards

**Comment by markushuber** [comment]
We recommend to use HTTPS for the webinterface: https://upri.box:4300
If this does not work try: https://upribox.local:4300
