### ISSUE TITLE
Nasa is in my device list

### ISSUE THREAD

**Issue by zionsuperfly** [usableprivacy/upribox#151]
Hello,

@ a moment i see NASA-Goddard Space Flight Center in my device list.
i assume this is not the normal way of working?

kind regards

**Comment by markushuber** [comment]
Hi @zionsuperfly,

The device is pretty ought and please be aware that the heuristics should improve the longer your device has been seen by your upribox. You can also change the device-name (with suggestions) if you click on the device name:
![image](https://user-images.githubusercontent.com/790934/70313895-c0ba3f80-1816-11ea-94f8-69d12d59fb15.png)
Then look through the suggestions or pick a custom name:
![image](https://user-images.githubusercontent.com/790934/70313952-d465a600-1816-11ea-9740-01c95c101717.png)
