### ISSUE TITLE
Improved WiFi settings

### ISSUE THREAD

**Issue by japo227** [usableprivacy/upribox#31]
Is it possible to add an option in WiFi Settings to:

(1) change the channel? 

Currently it's set to channel 9, I tried to change it to channel 1as I believe channel 9 interferes with my neighbors' wireless routers that mostly use channels 6 and 11 but the hostapd.conf file just gets overwritten by the automatic every 4-hour update.

(2) add another option in the WiFi settings to disable it totally as there is zero-config feature already or Apate which allows the use of existing wireless routers.

Just a thought... appreciate it. 

Thanks so much.

**Comment by markushuber** [comment]
Hi @japo227,

Thanks for the suggested improvements, we plan to include better WiFi configuration options in the next version of the upribox Software. The option to completely disable WiFi makes a lot of sense because of Apate, as you pointed out.

markus
