### ISSUE TITLE
Question more than an Issue - SSID password

### ISSUE THREAD

**Issue by jziggy101** [usableprivacy/upribox#32]
Is it possible to change the SSID passwords from within the SSH shell?  I am a relatively new linux users and I thought it would be nice to be able to change the SSID passwords from within the ssh shell instead of doing it from a wifi device.

**Comment by markushuber** [comment]
Hi @jziggy101,

Actually there is already a simple way to set the SSID from the command line: the `upri-config.py` script.
`sudo upri-config.py set_password newpassword` sets the password for the **silent SSID** whereas `sudo upri-config.py set_tor_password newpassword` changes the password for the **ninja SSID**.
