### ISSUE TITLE
.box TLD official

### ISSUE THREAD

**Issue by schmiedecker** [usableprivacy/upribox#33]
The TLD .box will become routable anytime soon, I'd recommend to change the local admin interface to https://my.upribox instead.

See also https://www.heise.de/newsticker/meldung/Neue-Top-Level-Domain-box-bringt-manche-Netze-durcheinander-3491185.html

**Comment by markushuber** [comment]
Thanks @schmiedecker,

This is currently not an issue because the upribox does not use a global DNS service to resolve **upri.box**.

markus

**Comment by schmiedecker** [comment]
Sure, but any admin with a misconfigured (external) DNS resolver will land
on the upcoming upri.box domain. Copy the interface, ask for the password,
done.

2016-11-19 21:07 GMT+01:00 Markus Huber <notifications@github.com>:

**Comment by markushuber** [comment]
The upribox intercepts and modifies any DNS request, so our current solution works independent of the used external DNS service. Thanks for bringing the issue up.
