### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by markushuber** [usableprivacy/upribox#37]
We put a lot of thought into the design of the upribox Software but have documented our design.
A proper documentation will help to explain and communicate the *security*, *privacy* and *networking* features of the upribox Software.
We are considering to use Sphinx, other suggestions are very welcome.

**Comment by ThorstenS-linux** [comment]
I´m also using sphinx with a slightly modified rtd-theme. Its perfect for man/html/pdf/epub output.
(especially manpages are super cool 👍 ).  
I think to go with sphinx is a good decision!

**Comment by markushuber** [comment]
upribox documentation will be hosted on readthedocs.org: 
[![Documentation Status](https://readthedocs.org/projects/upribox/badge/?version=latest)](http://upribox.readthedocs.io/en/latest/?badge=latest)
