### ISSUE TITLE
Raspberry Pi3

### ISSUE THREAD

**Issue by JimderDon** [usableprivacy/upribox#4]
Hey! :)

i run  upri on my old Pi2 that was realy fine and i used it with my mobile devices. Now i buy a pi3 and will turn it in to a upribox. My pi2 is in use for other things. The problem is it dont wanna start. Can you upload a image with Raspbian Jessie?!  Greetz Jim!

**Comment by markushuber** [comment]
You can now download the new Image form the Jessie branch: 
https://github.com/usableprivacy/upribox/tree/jessie

**Comment by JimderDon** [comment]
jeah realy cool thx !
