### ISSUE TITLE
Statistics do not work

### ISSUE THREAD

**Issue by cmalzer2** [usableprivacy/upribox#44]
After login to upri.box gui and changing to statistics I get only the circling circle. No statistics since a couple weeks. Logged in on mac.sierra with Opera and Safari - same result!
<img width="512" alt="screen shot 2017-01-22 at 22 12 17" src="https://cloud.githubusercontent.com/assets/22394681/22186038/f3e0a22a-e0ef-11e6-89bb-c6e34e96225d.png">

**Comment by markushuber** [comment]
Hi @cmalzer2,

Could please post the Software Version your box is running? (in the Admin menu)?

markus

**Comment by cmalzer2** [comment]
Hallo Markus,
 I use v0.7-26-g2fc2264
Christoph

**Comment by markushuber** [comment]
Hi Christoph,

You are already using the latest Software version - which seems good. We could however not reproduce the error on our test devices.

Have you tried rebooting your box to see if the problem still remains? (either via ssh or simply by un-plugging the power supply)

best Markus

**Comment by cmalzer2** [comment]
Hi Markus,
I do regular restarts due the great reliability of UPC/Vienna;-)
Anyhow I just did a restart via ssh, no change. I can give a Teamviewer remote access if you want!
Regards Christoph

**Comment by markushuber** [comment]
Hi Christoph, please send me an E-Mail: markus AT upribox DOT org
I am sure we find a suitable way for debugging, esp. because you live in Vienna as well. ;-)

m

**Comment by jziggy101** [comment]
Just stopped in to see if anything was new and saw this issue.  I had not tried to access the statistics for some time but it turns out I have the same issue.  Rotating circle and no statistics ever show.

I am on v.07-38-g00fc46f

**Comment by markushuber** [comment]
Thanks to @cmalzer2 we located the issue. We are currently testing a solution which should available to all upribox users, next week.

**Comment by markushuber** [comment]
commit #48 fixed the issue, statistics are responsive and displayed again.

**Comment by markushuber** [comment]
@cmalzer2 is still experiencing some issues, @jziggy101 does our fix work for you?

**Comment by markushuber** [comment]
issue is resolved, thanks @julianschritt for the fix.
