### ISSUE TITLE
Way to tell how many devices are logged into the Upri?Box?

### ISSUE THREAD

**Issue by jziggy101** [usableprivacy/upribox#62]
Is there a way to tell how many devices are logged into the UpriBox?  I know nothing on the admin page will tell me but I was wondering if something via the commandline would?  Maybe a new feature on the admin screen?
Thanks.

**Comment by julianschritt** [comment]
Hey @jziggy101,
We are currently working on the upribox 2.0 and a device overview with the possibility to configure each device separately will be a part of it. You can find more information about the planned features of the upribox 2.0 in our [blog](https://upribox.org/blog/2017/01/23/upribox2-protect-your-home-devices/).
