### ISSUE TITLE
Device vanishes from device overview

### ISSUE THREAD

**Issue by tobiasdam** [usableprivacy/upribox#92]
Currently, devices, that have not been determined online by `registrar` or `parse_user_agents` for more than one week, are not shown in the device overview.

If a device has a static IP (registrar won't work) and is configured to use "no mode" (parse_user_agents won't work). it appears to be offline forever.

**Comment by markushuber** [comment]
Any progress on this bug. @is151006 can you verify if the issue still exists?

**Comment by markushuber** [comment]
cronjob to probe for offline / no-mode devices every 1h.

**Comment by ThorstenS-linux** [comment]
to scan my network, I using this:
```
fping -g 192.168.2.0/24 -Q 3 -a
```
faster is this 
``
nmap -TAggressive -n -sS -p80 192.168.2.1 192.168.2.254 &> /dev/null
arp -a | fping -AaQ3
```

**Comment by tobiasdam** [comment]
fixed by  5ad79746b9bd30ff2a638b6a36835755836c1d3
