### ISSUE TITLE
Switch branch for legacy software

### ISSUE THREAD

**Issue by markushuber** [usableprivacy/upribox#95]
Fork the current `master` branch to a new branch called `jessie`.
In the master branch the pull branch should than be changed to `jessie`.

This preparation helps to fade out the 1.0 version of the upribox Software.

**Comment by tobiasdam** [comment]
Please remove the old jessie branch beforehand, so that I can create a new clean branch

**Comment by tobiasdam** [comment]
The pull request #105 needs to be merged into the current master branch, afterwards the master branch and also the new jessie_v1 branch will pull from jessie_ v1.
